#!/usr/bin/env bash

help()
{
  cat << HELP
Usage: console [OPTIONS] ARGS
  Options:
    -h | --help: Prints this help

  Args:
    hello: Prints Hello on the screen
HELP
}

hello()
{
  echo 'Hello world!'
}

main()
{
  ARG="$1"

  case "$ARG" in

    hello )
      hello
    ;;

    --help | -h )
      help
    ;;

    * )
      help
    ;;

  esac
}

main "$@"
exit 0
